### PR TITLE
Removable lines from header and footer

### PR DESCRIPTION
**Pull request by ruViolence**
Adds the ability to remove lines from a tab using a special value "#rm#". This will allow making various dynamically appearing lines using custom placeholders.

### CODE REVIEW

**Comment by NEZNAMY** [comment]
You already can use dynamic lines using "\n", which sounds easier to use as well.

**Comment by ruViolence** [comment]
Hmm, actually yes, but then I have to add a placeholder at the end of some line above, which might look a bit ugly in the config 😅

**Comment by NEZNAMY** [comment]
And now it will look ugly in both config and code.

**Comment by ruViolence** [comment]
To be honest, I did not realized right away that I could use \n to make this feature possible. Okay then, since it also adds some performance loss, I'll close this pull request.

**Pull request closed without merging**
