### PR TITLE
Added support for judgment of world or server.

### PR DESCRIPTION
**Pull request by Score2**
E.g:
```
disable-in-worlds:
-'example-*'
```
Then the player will not enable this feature in example-1 or example-2.

### CODE REVIEW

**Comment by NEZNAMY** [comment]
I was wondering why not just adding some logic into https://github.com/NEZNAMY/TAB/blob/master/shared/src/main/java/me/neznamy/tab/shared/features/types/Feature.java#L22-L35, sounds like that would do it just fine to me.

**Comment by Score2** [comment]
> ‎我想知道为什么不只是添加一些逻辑‎[‎到 https://github.com/NEZNAMY/TAB/blob/master/shared/src/main/java/me/neznamy/tab/shared/features/types/Feature.java#L22-L35，‎](https://github.com/NEZNAMY/TAB/blob/master/shared/src/main/java/me/neznamy/tab/shared/features/types/Feature.java#L22-L35)‎听起来像那样会做它只是罚款给我。应要求加载整个世界/服务器列表看起来没有必要。‎

Adding a group of servers is to accommodate when you are facing a large number of halls.
The numbers of these halls are usually uncontrollable. Sometimes there are many hall servers. It is not elegant to fill in the configuration file one by one, and it is very difficult to manage.

**Comment by Score2** [comment]
Maybe that part of the logic I wrote is not perfect. If so, can you add the requested feature?

**Comment by NEZNAMY** [comment]
Implemented in a much cleaner way.

**Pull request closed without merging**
