### PR TITLE
Updates and Velocity Deprecation Fix

### PR DESCRIPTION
**Pull request by JT122406**
Yes I know its not in the jar but still nice to keep it up to date for people wanting to use it by compiling themselves

### CODE REVIEW

**Comment by NEZNAMY** [comment]
Looks like you need to fix compilation.

**Comment by JT122406** [comment]
Yeah for some reason one of the repos are down

**Comment by JT122406** [comment]
Let me see whats going on because it compiled for me earlier

**Comment by JT122406** [comment]
All good now

**Pull request merged**
