### PR TITLE
Add %mspt%

### PR DESCRIPTION
**Pull request by ItzRiotz**
Only for PaperSpigot or forks of it.
I just did this for my server because I wanted to have it, but I can contribute if it's good enough? lol
Tried making it as compatible as possible for contribution and possible use of it.
Only displays current MSPT

### CODE REVIEW

**Comment by NEZNAMY** [comment]
How about replacing all of that with just
```
try {
	Class.forName("com.destroystokyo.paper.PaperConfig");
	placeholders.add(new ServerPlaceholder("%mspt%", 1000) {
		public String get() {
			try {
				return String.valueOf(roundDown.format(Bukkit.getAverageTickTime()));
			} catch(Exception e){
				return null;
			}
		}
	});
} catch (Exception e){
    //not paper
}
```
inside registerPlaceholders method?

**Comment by ItzRiotz** [comment]
Didn't think of that :)
Sure, it's much simpler to the way I approached it

**Comment by NEZNAMY** [comment]
Do you want to change the PR or should I just add it?

**Comment by ItzRiotz** [comment]
I'll change the PR

**Pull request closed without merging**
