### PR TITLE
Add a per-permission header/footer

### PR DESCRIPTION
**Pull request by ruViolence**
Adds the ability to set header/footer when a player has a certain permission.

### CODE REVIEW

**Comment by Tanguygab** [comment]
I think it could be even more interesting if you use conditions instead of just permissions, it could allow more things to be checked like regions and stuff =)

**Comment by ruViolence** [comment]
This is quite difficult to do, given that the tab is updated only when the player is connected to the server or change the world. And I don't want to fill this plugin with my spaghetti code. In any case, you can do it yourself if you need it :)

**Comment by Tanguygab** [comment]
true, maybe I'll try to look into it

**Comment by NEZNAMY** [comment]
I don't want any new features in the plugin. On top of that, permissions are usually separated with `.`, just like config sections, which will cause conflict.

**Comment by ruViolence** [comment]
Fixed a problem with dotted permissions. I think this feature would be useful for some people. On my server I use it to display a special header with a technical information about server performance to the staff players.

**Comment by NEZNAMY** [comment]
This change would make the configuration more complicated for everyone, but you are currently the only one interested in this. I believe this change made for your server should not cause confusion of everyone else.

**Pull request closed without merging**
