### PR TITLE
I want to be able to use getDataFolder

### PR DESCRIPTION
**Pull request by 130B**
This allows you to use custom plugin paths, including configuration files

### CODE REVIEW

**Comment by NEZNAMY** [comment]
The ConfigurationFile commit (https://github.com/NEZNAMY/TAB/pull/132/commits/3e94e13228480a2d3d901e290dd827c9a3031b79) would result in NoClassDefFoundError on bungeecord and velocity. The class is universal and i want to keep it like that.

**Comment by 130B** [comment]
> The ConfigurationFile commit ([3e94e13](https://github.com/NEZNAMY/TAB/commit/3e94e13228480a2d3d901e290dd827c9a3031b79)) would result in NoClassDefFoundError on bungeecord and velocity. The class is universal and i want to keep it like that.

There is also getDataFolder in BungeeCord, Maybe it can read the plugin path and pass parameters to that class as soon as the server is loaded.

**Comment by NEZNAMY** [comment]
That's possible, but.. why ?

**Comment by 130B** [comment]
For many duplicate sub-servers, it is not necessary to copy every directory, which can reduce unnecessary trouble

**Comment by NEZNAMY** [comment]
How do you even make .getDataFolder return something else than it does now ?

**Comment by A248** [comment]
There is a spigot startup flag which no one ever uses to change the /plugins/ directory.

**Comment by NEZNAMY** [comment]
I will consider it when i get more requests.

**Comment by NEZNAMY** [comment]
Both of the changed classes contain critical issues.
PlaceholderAPI downloader class points to wrong directory.
ConfigurationFile class would stop working on bungeecord.
I will add this myself.

**Pull request closed without merging**
