### PR TITLE
Update NetworkManager.java

### PR DESCRIPTION
**Pull request by ChimpGamer**
This should solve the NPE issues with NetworkManager.

### CODE REVIEW

**Comment by NEZNAMY** [comment]
Yes I already added null checks but didn't push to github yet.

**Comment by ChimpGamer** [comment]
And did that solve the issues?

**Comment by NEZNAMY** [comment]
I did exactly what you did (with 1 more null check). It turned stacktrace into a user-friendly error message. This is how I have it right now http://prntscr.com/uvmorz.

**Comment by ChimpGamer** [comment]
Yea that's perfect.

**Comment by NEZNAMY** [comment]
There's a great chance for github desktop to die if I merge this (like before) due to conflicts, do you want this accepted or is my code change acceptable for you?

**Comment by ChimpGamer** [comment]
Yours is fine.

**Comment by NEZNAMY** [comment]
Code pushed, can this be closed?

**Comment by ChimpGamer** [comment]
Yep, closed.

**Pull request closed without merging**
