### PR TITLE
Gradle 8.0.1 + changes for that update

### PR DESCRIPTION
**Pull request by JT122406**

### CODE REVIEW

**Comment by NEZNAMY** [comment]
Do you have a build available?

**Comment by JT122406** [comment]
> Do you have a build available?

Like a jar from this?

**Comment by NEZNAMY** [comment]
Yes

**Comment by JT122406** [comment]
> Yes. Github actions failed.

Meant to make this a draft have a few more things to tweak

**Comment by JT122406** [comment]
Once I do I will build

**Pull request closed without merging**
